// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2g8o7PsHqVd48zPE5LGof-Ri0mNB-Po4',
    appId: '1:612160474920:web:d4677bc1c411d2544e8a1d',
    messagingSenderId: '612160474920',
    projectId: 'easyshopping-dcb82',
    authDomain: 'easyshopping-dcb82.firebaseapp.com',
    storageBucket: 'easyshopping-dcb82.firebasestorage.app',
    measurementId: 'G-RV2TR4WMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVlBtdygo4bHjsT8P87G7aNvz3twlTUJw',
    appId: '1:612160474920:android:96878d5aeeaf913a4e8a1d',
    messagingSenderId: '612160474920',
    projectId: 'easyshopping-dcb82',
    storageBucket: 'easyshopping-dcb82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxjNztn-08APNvly8wtqqhZnM2OBvYTXw',
    appId: '1:612160474920:ios:bb2d29e0b309e20d4e8a1d',
    messagingSenderId: '612160474920',
    projectId: 'easyshopping-dcb82',
    storageBucket: 'easyshopping-dcb82.firebasestorage.app',
    iosClientId: '612160474920-vn1oklnsu3eh287q7l7s7mif6acbgkdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxjNztn-08APNvly8wtqqhZnM2OBvYTXw',
    appId: '1:612160474920:ios:bb2d29e0b309e20d4e8a1d',
    messagingSenderId: '612160474920',
    projectId: 'easyshopping-dcb82',
    storageBucket: 'easyshopping-dcb82.firebasestorage.app',
    iosClientId: '612160474920-vn1oklnsu3eh287q7l7s7mif6acbgkdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2g8o7PsHqVd48zPE5LGof-Ri0mNB-Po4',
    appId: '1:612160474920:web:ea0d0acb9851d60b4e8a1d',
    messagingSenderId: '612160474920',
    projectId: 'easyshopping-dcb82',
    authDomain: 'easyshopping-dcb82.firebaseapp.com',
    storageBucket: 'easyshopping-dcb82.firebasestorage.app',
    measurementId: 'G-8KBLC59G3D',
  );

}