// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WGpbRqZUqqezsGT9alty1JY4iUGAjF8',
    appId: '1:819445477129:web:f77a417dd9deb628fbadd8',
    messagingSenderId: '819445477129',
    projectId: 'easyshopping-8bd04',
    authDomain: 'easyshopping-8bd04.firebaseapp.com',
    storageBucket: 'easyshopping-8bd04.firebasestorage.app',
    measurementId: 'G-CL9CHD5ZZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjh8eBpM6jFThWAVV0rm2m6njJkF8nUXs',
    appId: '1:819445477129:android:d506cd4e8fbda0c2fbadd8',
    messagingSenderId: '819445477129',
    projectId: 'easyshopping-8bd04',
    storageBucket: 'easyshopping-8bd04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAus4OsiHqQMEWyrUm1j0xS3EhKemvpc90',
    appId: '1:819445477129:ios:e6953eda602503f0fbadd8',
    messagingSenderId: '819445477129',
    projectId: 'easyshopping-8bd04',
    storageBucket: 'easyshopping-8bd04.firebasestorage.app',
    iosBundleId: 'com.example.finalpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAus4OsiHqQMEWyrUm1j0xS3EhKemvpc90',
    appId: '1:819445477129:ios:e6953eda602503f0fbadd8',
    messagingSenderId: '819445477129',
    projectId: 'easyshopping-8bd04',
    storageBucket: 'easyshopping-8bd04.firebasestorage.app',
    iosBundleId: 'com.example.finalpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1WGpbRqZUqqezsGT9alty1JY4iUGAjF8',
    appId: '1:819445477129:web:5be23867296fd276fbadd8',
    messagingSenderId: '819445477129',
    projectId: 'easyshopping-8bd04',
    authDomain: 'easyshopping-8bd04.firebaseapp.com',
    storageBucket: 'easyshopping-8bd04.firebasestorage.app',
    measurementId: 'G-E4NNR89353',
  );
}
